"""
Building WAPB functions from https://dl.acm.org/doi/abs/10.1007/s12095-019-00374-6

To obtain a WPB function the construction as to be initialised with a sequence c=[1,0,0,...,0,-1] (e.g, c=[1,0,0,0,-1]).
See Remark Remark 1 of https://ia.cr/2023/110.
"""

# This file was *autogenerated* from the file src/algebraic_immunity/boolean_functions/known_boolean_functions/TL19.sage
from sage.all_cmdline import *  # import sage library

_sage_const_2 = Integer(2);
_sage_const_0 = Integer(0);
_sage_const_1 = Integer(1)
import itertools
from sage.crypto.boolean_function import BooleanFunction
import random


def LT_Wi(k, i, rel):
    """Returns  W^{rel}_(2k,i) for LT constructions, i.e. subset of the set
    of all vectors (x,y) in F2^{2k} with Hamming weight i and such that Hw(x)~rel~Hw(y).


    Args:
        k (int): 2k is the size of the vectors
        i (int): hamming weight
        rel (string): "Eq" for = and "Gr" for >.

    Returns:
        list:  the list of all elements of W^{rel}_(2k,i)
    """
    n = _sage_const_2 * k
    Fk1 = itertools.product(range(_sage_const_2), repeat=k)
    if rel == "Eq":
        W = []
        for x in Fk1:
            Fk2 = itertools.product(range(_sage_const_2), repeat=k)
            hx = hw(x)
            if hx == i // _sage_const_2:
                for y in Fk2:
                    hy = hw(y)
                    if (hy == i // _sage_const_2) and (hx + hy == i): W.append(x + y)
    elif rel == "Gr":
        W = []
        for x in Fk1:
            Fk2 = itertools.product(range(_sage_const_2), repeat=k)
            hx = hw(x)
            for y in Fk2:
                hy = hw(y)
                if (hx + hy == i) and hx > hy:
                    W.append(x + y)
    return W


def LT_WG(k):
    """
    Returns the set W^> the union of W^{>}_(2k,i) for i=0,...,2k.

    Args:
        k (int): 2k is the size of the vectors

    Returns:
        set: W^>
    """
    n = _sage_const_2 * k
    W = set(LT_Wi(k, _sage_const_0, "Gr"))
    for i in range(_sage_const_0, n + _sage_const_1):
        Wi = LT_Wi(k, i, "Gr")
        for w in Wi: W.add(w)
    return W


def LT_Ui(k, i, c):
    """Returns an arbitrary subset  Ui of W^{=}_(2k,i) of cardinality (|W^{=}_(2k,i)|+c)/2

    Args:
        k (int): 2k is the size of the vectors
        i (int): hamming weight
        c (int): c in {0,1,-1} is the cardinality corrections

    Returns:
        set: Ui
    """
    if mod(i, _sage_const_2) == _sage_const_1:
        return []
    else:
        W = LT_W(k, i, "Eq")
        w = len(W)
        ui = (w + c) // _sage_const_2
        U = random.sample(W, ui)
        assert len(U) == ui
        return U


def LT_U(k, c):
    """Returns the union U of subsets  U_{2i} of W^{=}_(2k,2i) of cardinality (|W^{=}_(2k,2i)|+c[i])/2
       for k=0..k+1

    Args:
        k (int): 2k is the size of the vectors
        c (list): sequence of lenght k+1 over {−1, 0, 1} suck that c[i] = 0 if {k choose i} is event, and c[i] = +/-1 if odd.

    Returns:
        set: U
    """
    n = _sage_const_2 * k
    U = set(LT_Ui(k, _sage_const_0, c[_sage_const_0]))
    for i in range(_sage_const_1, k + _sage_const_1):
        U2i = LT_Ui(k, _sage_const_2 * i, c[i])
        for w in U2i: U.add(w)
    return U


def LT_is_valid_seq(c, k):
    """Checks if c is a valid input sequence for LT_U(k,c).

    Args:
        c (list): sequence over {−1, 0, 1} of lenght k+1
        k (int): 2k is the size of the vectors

    Returns:
        bool: True iff valid
    """
    sc = _sage_const_0
    for j in range(k + _sage_const_1):
        bi = binomial(k, j)
        # print(bi,c[j])
        if abs(c[j]) != mod(bi, _sage_const_2):
            return False
        sc += c[j]
    if sc != _sage_const_0: return False
    return True


def LT_from_seq(c, k):
    """Returns a boolean function function in n=2k variables from TL construction with a given sequence as input

    Args:
        c (list): sequence of lenght k+1 over {−1, 0, 1} suck that c[i] = 0 if {k choose i} is event, and c[i] = +/-1 if odd.
        k (int): 2k is the size of the vectors

    Returns:
        BooleanFunction: function from TL family
    """
    n = _sage_const_2 * k
    assert LT_is_valid_seq(c, k)
    WG = LT_WG(k)
    U = LT_U(k, c)
    U.union(WG)
    print(len(U))
    Lf = []
    for d in range(_sage_const_2 ** n):
        v = bin(d)[_sage_const_2:]
        v = (n - len(v)) * "0" + v
        v = tuple(vector(v, ZZ))
        if v in U:
            Lf += [_sage_const_1]
        else:
            Lf += [_sage_const_0]
    print(Lf)
    return BooleanFunction(Lf)


def LT_gr(v, k):
    x = v[:k]
    y = v[k:]
    return
    hw(x) > hw(y)


def LT_bin_to_int(v): return int("".join(str(i) for i in v), _sage_const_2)


def LT_WPB_rand(n):
    """
    Returns a WPB function in n variables sampled uniformly at random from TL family

    Args:
        n (int): number of variables

    Returns:
        BooleanFunction: TL-Boolean function in n variables that is WPB
    """
    k = n // _sage_const_2
    vf = vector(ZZ, _sage_const_2 ** n)
    vf[-_sage_const_1] = _sage_const_1
    for d in range(_sage_const_2 ** n):
        v = bin(d)[_sage_const_2:]
        v = (n - len(v)) * "0" + v
        x = v[:k]
        y = v[k:]
        hx = hw(x)
        hy = hw(y)
        if hx > hy: vf[d] = _sage_const_1
    for j in range(_sage_const_1, k):
        W = LT_Wi(k, _sage_const_2 * j, "Eq")
        U = random.sample(W, len(W) // _sage_const_2)
        for v in U: vf[LT_bin_to_int(v)] = _sage_const_1
    return BooleanFunction(list(vf))


def hw(x):
    """Compute the hamming weight of a vector x"""
    x = vector(ZZ, x)
    w = vector(ones_matrix(ZZ, _sage_const_1, len(x)))
    return w * x


tl_truth_table = {
    8: BooleanFunction([
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 0,
        0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,
        0,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        1, 1,
        1,
        1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 0,
        0,
        1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 0,
        0,
        1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0,
        0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
}
